// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package by.conspect.model;

import by.conspect.db.SystemUserRepository;
import by.conspect.model.SystemUserDataOnDemand;
import by.conspect.model.SystemUserIntegrationTest;
import by.conspect.service.SystemUserService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SystemUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SystemUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SystemUserIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SystemUserIntegrationTest: @Transactional;
    
    @Autowired
    private SystemUserDataOnDemand SystemUserIntegrationTest.dod;
    
    @Autowired
    SystemUserService SystemUserIntegrationTest.systemUserService;
    
    @Autowired
    SystemUserRepository SystemUserIntegrationTest.systemUserRepository;
    
    @Test
    public void SystemUserIntegrationTest.testCountAllSystemUsers() {
        Assert.assertNotNull("Data on demand for 'SystemUser' failed to initialize correctly", dod.getRandomSystemUser());
        long count = systemUserService.countAllSystemUsers();
        Assert.assertTrue("Counter for 'SystemUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SystemUserIntegrationTest.testFindSystemUser() {
        SystemUser obj = dod.getRandomSystemUser();
        Assert.assertNotNull("Data on demand for 'SystemUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SystemUser' failed to provide an identifier", id);
        obj = systemUserService.findSystemUser(id);
        Assert.assertNotNull("Find method for 'SystemUser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SystemUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SystemUserIntegrationTest.testFindAllSystemUsers() {
        Assert.assertNotNull("Data on demand for 'SystemUser' failed to initialize correctly", dod.getRandomSystemUser());
        long count = systemUserService.countAllSystemUsers();
        Assert.assertTrue("Too expensive to perform a find all test for 'SystemUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SystemUser> result = systemUserService.findAllSystemUsers();
        Assert.assertNotNull("Find all method for 'SystemUser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SystemUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SystemUserIntegrationTest.testFindSystemUserEntries() {
        Assert.assertNotNull("Data on demand for 'SystemUser' failed to initialize correctly", dod.getRandomSystemUser());
        long count = systemUserService.countAllSystemUsers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SystemUser> result = systemUserService.findSystemUserEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SystemUser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SystemUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SystemUserIntegrationTest.testFlush() {
        SystemUser obj = dod.getRandomSystemUser();
        Assert.assertNotNull("Data on demand for 'SystemUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SystemUser' failed to provide an identifier", id);
        obj = systemUserService.findSystemUser(id);
        Assert.assertNotNull("Find method for 'SystemUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySystemUser(obj);
        Integer currentVersion = obj.getVersion();
        systemUserRepository.flush();
        Assert.assertTrue("Version for 'SystemUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SystemUserIntegrationTest.testUpdateSystemUserUpdate() {
        SystemUser obj = dod.getRandomSystemUser();
        Assert.assertNotNull("Data on demand for 'SystemUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SystemUser' failed to provide an identifier", id);
        obj = systemUserService.findSystemUser(id);
        boolean modified =  dod.modifySystemUser(obj);
        Integer currentVersion = obj.getVersion();
        SystemUser merged = systemUserService.updateSystemUser(obj);
        systemUserRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SystemUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SystemUserIntegrationTest.testSaveSystemUser() {
        Assert.assertNotNull("Data on demand for 'SystemUser' failed to initialize correctly", dod.getRandomSystemUser());
        SystemUser obj = dod.getNewTransientSystemUser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SystemUser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SystemUser' identifier to be null", obj.getId());
        systemUserService.saveSystemUser(obj);
        systemUserRepository.flush();
        Assert.assertNotNull("Expected 'SystemUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SystemUserIntegrationTest.testDeleteSystemUser() {
        SystemUser obj = dod.getRandomSystemUser();
        Assert.assertNotNull("Data on demand for 'SystemUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SystemUser' failed to provide an identifier", id);
        obj = systemUserService.findSystemUser(id);
        systemUserService.deleteSystemUser(obj);
        systemUserRepository.flush();
        Assert.assertNull("Failed to remove 'SystemUser' with identifier '" + id + "'", systemUserService.findSystemUser(id));
    }
    
}
